--- #Connect to AWS env
- hosts: localhost
  vars_files:
    - keys.yml
  tasks:
  - name: Get EC2 Instance list.
    ec2_instance_facts:
        aws_access_key: '{{ AWS_ACCESS_KEY_ID }}'
        aws_secret_key: '{{ AWS_SECRET_ACCESS_KEY }}'
        region: '{{ AWS_REGION }}'
    register: output
  - name: Display instance list
    debug: 
        var: output.instances 
